# Generated by Django 3.1.1 on 2020-11-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Snippet',
        ),
    ]
