# Generated by Django 3.1.1 on 2020-11-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_auto_20201112_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_of_project', models.CharField(choices=[('W', 'Workshopping'), ('G', 'Game'), ('P', 'Productivity')], default='W', max_length=1)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.snippet')),
            ],
        ),
        migrations.DeleteModel(
            name='UsuageCounter',
        ),
    ]
