# Generated by Django 3.1.1 on 2020-11-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_auto_20201113_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagecounter',
            name='date',
            field=models.DateField(verbose_name='Usage Date'),
        ),
    ]
