# Generated by Django 3.1.1 on 2020-11-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_auto_20201116_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagecounter',
            old_name='type_of_project',
            new_name='project_type',
        ),
    ]
