# Generated by Django 3.1.1 on 2020-11-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_auto_20201116_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagecounter',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
