# Generated by Django 3.1.1 on 2020-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_auto_20201116_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagecounter',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='usagecounter',
            name='type',
            field=models.CharField(choices=[('W', 'Workshopping'), ('G', 'Game'), ('P', 'Productivity')], default='W', max_length=1),
        ),
    ]
