# Generated by Django 3.1.1 on 2020-11-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0014_auto_20201118_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Used',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='used',
            field=models.ManyToManyField(to='snippets.Used'),
        ),
    ]
